# Generated by Django 4.1.4 on 2022-12-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='user',
        ),
    ]
