# Generated by Django 4.1.4 on 2022-12-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_name_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_corrente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventarios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo_nao_corrente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passivo_corrente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passivo_nao_corrente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premio_de_emissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservas_nao_distribuidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucros_acumulados', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
