# Generated by Django 4.1.4 on 2022-12-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_balanco_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanco',
            old_name='nome',
            new_name='ano',
        ),
    ]
