# Generated by Django 4.1.4 on 2022-12-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_nome_balanco_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanco',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
    ]
