# Generated by Django 4.1.4 on 2022-12-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_balanco_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanco',
            name='activo_corrente',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='activo_nao_corrente',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='caixa',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='capital_social',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='inventarios',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='lucros_acumulados',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='passivo_corrente',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='passivo_nao_corrente',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='premio_de_emissao',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='reservas_nao_distribuidas',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.CreateModel(
            name='TableDeDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divida_bruta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.balanco')),
            ],
        ),
    ]
