# Generated by Django 4.1.4 on 2022-12-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_rename_divida_bruta_tablededivida_divida_liquida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablededivida',
            old_name='divida_liquida',
            new_name='divida_bruta',
        ),
    ]
