# Generated by Django 4.1.4 on 2022-12-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_rename_divida_liquida_tablededivida_divida_bruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablededivida',
            options={'verbose_name': 'Table De Divida', 'verbose_name_plural': 'Table De Divida'},
        ),
    ]
