# Generated by Django 4.1.4 on 2022-12-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_demonstracaoderesultados_alter_balanco_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanco',
            name='activo_corrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='activo_nao_corrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='caixa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='capital_social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='inventarios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='lucros_acumulados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='passivo_corrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='passivo_nao_corrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='premio_de_emissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='reservas_nao_distribuidas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='EBIT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='dividendo_declarados_e_pagos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='lucro_antes_de_imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='lucro_liquido_depois_de_imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='lucros_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='numero_medio_ponderado_de_acoes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='vendas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tablededivida',
            name='divida_bruta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
