# Generated by Django 4.1.4 on 2022-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_balanco_activo_corrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstracaoderesultados',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
    ]
