# Generated by Django 4.1.4 on 2022-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_tablededivida_balanco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50, unique=True),
        ),
    ]
