# Generated by Django 4.1.4 on 2022-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_demonstracaoderesultados_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemonstracaoDeFluxoDeCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, default='2015', max_length=50, unique=True)),
                ('fundo_gerados_das_actividades_operacionais', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('fundos_utilizados_em_actividades_de_investimento', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('fundos_introduzidos_atraves_de_actividades_de_financiamento', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('acrescimo_ou_decrescimo_em_caixa_e_equivalentes_de_caixa', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Demonstracao De Fluxos De Caixas',
            },
        ),
    ]
