# Generated by Django 4.1.4 on 2022-12-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_demonstracaodefluxodecaixa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demonstracaodefluxodecaixa',
            old_name='fundo_gerados_das_actividades_operacionais',
            new_name='fundos_gerados_das_actividades_operacionais',
        ),
    ]
