# Generated by Django 4.1.4 on 2022-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_rename_fundo_gerados_das_actividades_operacionais_demonstracaodefluxodecaixa_fundos_gerados_das_acti'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresDeRentabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, default='2015', max_length=50, unique=True)),
            ],
        ),
    ]
