# Generated by Django 4.1.4 on 2022-12-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_indicadoresdecrescimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresDeEndividamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, default='2015', max_length=50, unique=True)),
            ],
            options={
                'ordering': ('ano',),
            },
        ),
    ]
