# Generated by Django 4.1.4 on 2022-12-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_metricasporaccao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotacoesDasAcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('nome_da_empresa', models.CharField(max_length=150)),
                ('preco_da_acao', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Cotacao Da Acao',
                'verbose_name_plural': 'Cotacoes Das Acoes',
            },
        ),
    ]
