# Generated by Django 4.1.4 on 2022-12-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_alter_cotacoesdasacoes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacoesdasacoes',
            name='preco_da_acao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
