# Generated by Django 4.1.4 on 2022-12-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_metricasporaccao_nome_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricasporaccao',
            name='nome_da_empresa',
            field=models.CharField(blank=True, default='CDM', max_length=150),
        ),
    ]
