# Generated by Django 4.1.4 on 2022-12-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_metricasporaccao_nome_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablededivida',
            name='balanco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.balanco'),
        ),
    ]
