# Generated by Django 4.1.4 on 2022-12-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='CDM', max_length=125, unique=True),
        ),
    ]
