# Generated by Django 4.1.4 on 2022-12-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_alter_company_options_alter_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('id',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
