# Generated by Django 4.1.4 on 2023-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0043_balanco_disconto_de_premio_das_acoes_proprias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanco',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
    ]
