# Generated by Django 4.1.4 on 2023-01-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_demonstracaoderesultados_nome_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
    ]
