# Generated by Django 4.1.4 on 2023-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_alter_demonstracaoderesultados_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricasporaccao',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
    ]
