# Generated by Django 4.1.4 on 2023-01-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0047_alter_metricasporaccao_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricasporaccao',
            options={'ordering': ('nome_da_empresa',)},
        ),
    ]
