# Generated by Django 4.1.4 on 2023-01-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0048_alter_metricasporaccao_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricasPorAccao',
        ),
    ]
