# Generated by Django 4.1.4 on 2023-01-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0049_delete_metricasporaccao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasPorAccao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(blank=True, default='2015', max_length=50)),
                ('nome_da_empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.company')),
            ],
            options={
                'ordering': ('nome_da_empresa',),
            },
        ),
    ]
