# Generated by Django 4.1.4 on 2023-01-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_metricasporaccao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricasporaccao',
            options={'ordering': ('-ano',)},
        ),
    ]
