# Generated by Django 4.1.4 on 2023-01-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0052_tablededivida_nome_da_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablededivida',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
        migrations.AlterField(
            model_name='tablededivida',
            name='balanco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.balanco'),
        ),
    ]
