# Generated by Django 4.1.4 on 2023-01-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0053_tablededivida_ano_alter_tablededivida_balanco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablededivida',
            name='balanco',
        ),
    ]
