# Generated by Django 4.1.4 on 2023-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0055_indicadoresderentabilidade_nome_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadoresderentabilidade',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
    ]
