# Generated by Django 4.1.4 on 2023-01-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0056_alter_indicadoresderentabilidade_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstracaoderesultados',
            name='vendas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
