# Generated by Django 4.1.4 on 2023-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0062_indicadoresdeendividamento_nome_da_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstracaodefluxodecaixa',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicadoresdecrescimento',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicadoresdeeficiencia',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicadoresdeendividamento',
            name='ano',
            field=models.CharField(blank=True, default='2015', max_length=50),
        ),
    ]
