# Generated by Django 4.1.4 on 2023-01-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0063_alter_demonstracaodefluxodecaixa_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector_de_actuacao',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('seguros', 'Seguros'), ('energia-hidroelectrica', 'Energia Hidroelectrica'), ('portagem', 'Portagem')], default='bebidas', max_length=100),
        ),
    ]
